### ISSUE TITLE
Where do I find a list of available insiders commits?

### ISSUE THREAD

**Issue by jespertheend** [bpasero/vscode-bisect#5]
I often want to bisect a range where I know a bug didn't exist about a month ago. What's a good way to figure out what the best commit to pick is?

**Comment by bpasero** [comment]
This tool would not offer that, the idea is to just let it run and find the offender after max. 8 attempts. Only in very specific cases where you know the versions should you provide that info to speed up, but that info is optional (maybe that is not clear?).

**Comment by jespertheend** [comment]
Makes sense, I didn't expect this tool to offer this. I was just wondering, since this tool asks me to provide an (optional) commit, if there was a list online somewhere :)

**Comment by bpasero** [comment]
No there is no list officially sorry!
