### ISSUE TITLE
Unable to find executable

### ISSUE THREAD

**Issue by jespertheend** [bpasero/vscode-bisect#9]
os: `macOS 12.5 (21G72)`
node: `v18.5.0`

Steps to reproduce:
- run `npx vscode-bisect --verbose --clean`
- When asked for a commit hash, leave empty and hit enter

The output gives:
```
✔ Commit of released insiders build that reproduces the issue (leave empty to pick the latest build) … 
✔ Commit of released insiders build that does not reproduce the issue (leave empty to pick the oldest build) … 
[build] total 200 builds with roughly 8 steps
[build] using /var/folders/91/c18rf4qj42jcm0rxfzgtxk200000gn/T/vscode-bisect/.builds/345f572e37ca69dc143c9fecb5f851fba9fcce8c/vscode-server-darwin-web.zip for the next build to try
[build] downloading build from https://az764295.vo.msecnd.net/insider/345f572e37ca69dc143c9fecb5f851fba9fcce8c/vscode-server-darwin-web.zip...
[build] unzipping build to /var/folders/91/c18rf4qj42jcm0rxfzgtxk200000gn/T/vscode-bisect/.builds/345f572e37ca69dc143c9fecb5f851fba9fcce8c...
[build] starting build 345f572e37ca69dc143c9fecb5f851fba9fcce8c...
Error: [build] unable to find executable /var/folders/91/c18rf4qj42jcm0rxfzgtxk200000gn/T/vscode-bisect/.builds/345f572e37ca69dc143c9fecb5f851fba9fcce8c/vscode-server-darwin-web/bin/code-server-insiders on disk. Is the archive corrupt?
You can run vscode-bisect --verbose for more detailed output and vscode-bisect --clean for a fresh start without caches.
```

When inspecting the contents of `/var/folders/91/c18rf4qj42jcm0rxfzgtxk200000gn/T/vscode-bisect/.builds/345f572e37ca69dc143c9fecb5f851fba9fcce8c` it only seems to contain `vscode-server-darwin-web.zip`, no unarchived files

**Comment by jespertheend** [comment]
I guess 345f572e37ca69dc143c9fecb5f851fba9fcce8c is corrupt, Archive Utility doesn't seem to be able to unarchive it either.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/2737650/183932414-f75df039-3e48-45bf-8683-ca65996a608d.png">

**Comment by jespertheend** [comment]
https://az764295.vo.msecnd.net/insider/345f572e37ca69dc143c9fecb5f851fba9fcce8c/vscode-server-darwin-web.zip responds with a 404 so I guess that's the issue.

**Comment by bpasero** [comment]
Sorry for being late, https://github.com/bpasero/vscode-bisect/commit/5ad403f240e667e9ba4716329c5fc153a0adff24 should fix this.
